### ISSUE TITLE
Error: Invariant Violation: ManifestComponent.render(): A valid ReactComponent must be returned.

### ISSUE THREAD

**Issue by moroshko** [whetstone/redux-devtools-diff-monitor#13]
I'm trying to use `redux-devtools-diff-monitor` with `React v0.14.0-rc1` and `redux-devtools v2.1.2`.

I'm getting the following error:

![](http://dl.dropbox.com/u/1893981/Screenshots/5l4s.png)

To reproduce the issue:
```
$ git clone git@github.com:moroshko/accessible-colors.git
$ cd accessible-colors
$ git checkout diff-monitor
$ npm install
$ npm start
```

Open `http://localhost:3000/dist/index.html` in a browser and you'll see the error above.

Note that if I change `DiffMonitor` to `LogMonitor`, everything works fine.

**Comment by okonet** [comment]
+1

**Comment by iktl** [comment]
Thanks for this report, I'm hoping to block time tonight to resolve. Will keep you posted.

**Comment by moroshko** [comment]
@iktl Any update on this?

**Comment by iktl** [comment]
@moroshko 

This should be resolved now; can you re-test on your end with the 2.0 version and let me know? I'll close this or not upon your confirmation.

**Comment by moroshko** [comment]
@iktl It works now, but I get the following warning:
> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ManifestActionComponent`.

[Demo](https://dl.dropboxusercontent.com/u/1893981/redux-devtools-diff-monitor-warning.mov)
