### ISSUE TITLE
Update to redux 3

### ISSUE THREAD

**Issue by hpaul** [whetstone/redux-devtools-diff-monitor#19]
Tried this monitor and got more problems than help I wanted.

First, I'm using React server side rendering and 'mousetrap' could not bind to window since it not exist.
Second, it's using Redux 2, but I see commits from 13 days ago and redux got to version 3 about a month ago.

It's promising, if I got time I'll update myself.

**Comment by iktl** [comment]
I've updated in 3.0 to use React 0.14 and Redux 3 so you should have no difficulties w.r.t versioning now. 

I don't use server-side rendering but if you would like to add some logic around mousetrap not binding in a server-rendered environment I welcome the PR.
