### ISSUE TITLE
Update to Redux DevTools 3.0 Beta 2

### ISSUE THREAD

**Issue by gaearon** [whetstone/redux-devtools-diff-monitor#20]
Redux DevTools beta is [out with breaking changes](https://github.com/gaearon/redux-devtools/releases/tag/v3.0.0-beta-2). For monitors, there are a few of them:

* Instead of receiving action creators in `props`, you now get `dispatch` in props and have to `import { ActionCreators } from 'redux-devtools'` to get access to `commit`, `rollback`, etc

* The action props are now indexed by ID, so instead of `stagedActions` and `skippedActions` you get `actionsById`, `stagedActionIds` and `skippedActionIds`. `toggleAction()` now accepts `id` instead of `index`. To grab vanilla action object by ID, use `this.props.actionsById[id].action`.

* The monitor now has to export a `reducer` static property. For what it's worth, it could be a no-op function, but it must exist. In more interesting case, it will be `(state, action, props) => nextState` function where `state` is the monitor's own state available to it as `monitorState` prop. You are free to use it to let monitor react to any action and remember any data. This is why `setMonitorState` prop is gone.

* Monitors shouldn't take care anymore of `isVisible` (hiding or showing themselves) or doing so on special key presses. We're moving towards a composable monitor model, where you'd use a special [dock monitor](https://github.com/gaearon/redux-devtools-dock-monitor) to contain other monitor. Therefore monitors should only be worried about rendering themselves.

[The diff of the default LogMonitor](https://github.com/gaearon/redux-devtools-log-monitor/compare/v1.0.0-alpha-2...v1.0.0-beta-2) can serve as an inspiration for these changes.
[You can try the new version of Redux DevTools on the `next` branch.](https://github.com/gaearon/redux-devtools/tree/next)

Please let me know if you find any issues. The API might change slightly in the final release, but this is pretty close, and it involves some work, so let me know if you need any help.

**Comment by gtfiorentino** [comment]
Thanks for the details! We'll get to updating this shortly and let you know if there are questions.

**Comment by gtfiorentino** [comment]
@iktl check out the `redux-devtools-3` branch, which is a WIP update.

I switched out the action props for action creators that get dispatched and updated the staged and skipped action props.

There are a few other things to do (currently getting a `missing required context` error when running the example app), but I probably won't have time tomorrow, so if you want to take a look go for it. We should try to get this change working in a branch this week.
