### ISSUE TITLE
Don't calculate differences in state when the window is hidden

### ISSUE THREAD

**Issue by benarmston** [whetstone/redux-devtools-diff-monitor#21]
First of all thanks for creating this. It has been really useful in helping me to understand what is happening with my redux state.

Unfortunately, it has also been grinding my application to halt. I have tracked this down to repeated calculation of the state diff and have implemented a very simple fix for my purposes.  The fix that I came up with was to not render any of the action reports when the tool is not being displayed.

A more thorough solution might involve caching the calculation of the state diffs in some manner; but I don't have time to into that right now.

If you'd like to make use of the changes I made they can be seen at https://github.com/benarmston/redux-devtools-diff-monitor/commit/3b563abc20b685baebd761d0b8a1131b3da9a3e4.  I can create a pull request for these, or you are free to copy them across as you prefer.  They were made against branch 2.0.3.

**Comment by gtfiorentino** [comment]
Hey @benarmston - glad you've gotten use out of this project!

We're happy to accept a PR for your change. If it helps you, I'm sure it will help others.

Note that we're currently working on updating to support the next version of Redux DevTools, so there may be some differences in the implementation going forward, but we'll look into that as we work on the upgrade.

**Comment by iktl** [comment]
I've published a beta release for performance fixes, wherein it recalculates the diff only when the action is expanded and the store mutation data is visible. You can install it with `npm install redux-devtools-diff-monitor@beta`. Can you try this and see if it resolves the performance issue?

**Comment by iktl** [comment]
This should be addressed in 5.0.2. Please reopen or file a new ticket if this continues to be an issue.
