### ISSUE TITLE
npm version 4.0.0 is missing the built lib/ directory

### ISSUE THREAD

**Issue by kellycampbell** [whetstone/redux-devtools-diff-monitor#23]
Installing redux-devtools-diff-monitor 4.0.0 from npm leaves a broken install which is missing the built files in lib/

Workaround is to go into node_modules/redux-devtools-diff-monitor and run:
npm install
npm run build

**Comment by gtfiorentino** [comment]
Well that's no good. Should have time to fix by tomorrow. Thanks for reporting!

**Comment by gtfiorentino** [comment]
I've just published v4.0.1, which should fix this issue.
