### ISSUE TITLE
Display action as JSON object instead of string

### ISSUE THREAD

**Issue by jasonslyvia** [whetstone/redux-devtools-diff-monitor#24]
Following scenarios would be much eased if we can check action as object like  what `LogMonitor` do.
 
![image](https://cloud.githubusercontent.com/assets/1336484/12192104/df111b04-b616-11e5-89c0-e5a08b443981.png)

**Comment by iktl** [comment]
Hi Jason – do you mean as a collapsible / expandable tree-view of the state object?

**Comment by jasonslyvia** [comment]
Yes, that's exactly what I mean. 

But the way, using `diff-monitor` significantly slows my app down when action fires frequently, while using `log-monitor` eased this situation, but not much better. So I can't confirm it's a `diff-monitor` issue or just `redux-devtool` issue.

**Comment by iktl** [comment]
Possibly us, as we have had similar reports before. I'll have a look at implementing the treeview style and check performance as well. What's your action trigger rate, roughly?

**Comment by jasonslyvia** [comment]
It depends, when typing in a `<input>`, it fires an action every time `onChange` callback is called.

**Comment by iktl** [comment]
I've published a beta release for performance fixes, wherein it recalculates the diff only when the action is expanded and the store mutation data is visible. You can install it with `npm install redux-devtools-diff-monitor@beta`. Can you try this and see if it resolves the performance issue?

**Comment by kjr247** [comment]
@iktl 
I've an idea for styling the diffs from string into an object view, but I haven't gotten around to it. Here is what I had in mind for starters. As for making them collapsible, kinda seems like a waste, perhaps just give each action window, more size. I kinda like the sizing of about 3 actions on the screen if they are all open. 

[](http://jsfiddle.net/unlsj/)

**Comment by iktl** [comment]
I have added a tree-view for actions in 5.0.2. I am hoping to potter around with adding this to the state diff too, but that may take some time. Please re-open this if there are other issues.
