### ISSUE TITLE
Slows down app when action is fired

### ISSUE THREAD

**Issue by vjpr** [whetstone/redux-devtools-diff-monitor#25]
When an action is fired the entire app slows down while the devtools updates.

In #24 there was also some discussion of slowness. Apparently the diffing is expensive.

This is the most useful devtools monitor so far, would love to see this slowness resolved so that it is usable.

**Comment by iktl** [comment]
Thanks for the kind words – I have some time in the next week before I start a new job so I'll work some optimisations. I think the easiest method will be to compute the diff only when that action is expanded, so I'll probably overhaul a lot of the internals while I'm at it.

**Comment by iktl** [comment]
I've published a beta release for performance fixes, wherein it recalculates the diff only when the action is expanded and the store mutation data is visible. You can install it with `npm install redux-devtools-diff-monitor@beta`. Can you try this and see if it resolves the performance issue?

**Comment by iktl** [comment]
This should be addressed in 5.0.2. Please reopen or file a new ticket if this continues to be an issue.
