### ISSUE TITLE
Unsupported CSS warning on Firefox

### ISSUE THREAD

**Issue by choyongjoon** [whetstone/redux-devtools-diff-monitor#27]
When the monitor is updated, I got warning 

Unsupported CSS property "WebkitUserSelect$" in component "ManifestActionComponent"

I'm using Firefox 44.0.2 on Mac OS X El Capitian

**Comment by kjr247** [comment]
We can use autoprefixer to solve unsupported css issues. https://github.com/postcss/autoprefixer

**Comment by iktl** [comment]
This should be addressed in 5.0.2 with the change to Aphrodite and autoprefixing built in. Please reopen or file a new ticket if this continues to be an issue.
