### ISSUE TITLE
Consider changing the toggle combo

### ISSUE THREAD

**Issue by jchapron** [whetstone/redux-devtools-diff-monitor#3]
Ctrl+] is not accessible on a keyboard with AZERTY layout.

(Part of) Europe says thanks ! 
Looks awesome anyway :)

**Comment by iktl** [comment]
I might add in support for `Ctrl+H` to be consistent with @gaeron's default implementation; ideally all monitors should be as replaceable as possible in my mind. Look for this later tonight.
